AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'config.ru'
    - '.git/**/*'
    - './vendor/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Max: 125

Metrics/CyclomaticComplexity:
  Max: 15

# Use code climate's metrics measurement rather than rubocop's
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'lib/app/models/util/validation.rb'
